//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brupper.AspNetCore.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brupper.AspNetCore.Identity.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó adatainak módosítása.
        /// </summary>
        internal static string account_settings {
            get {
                return ResourceManager.GetString("account_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozva.
        /// </summary>
        internal static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Város.
        /// </summary>
        internal static string customer_address_city {
            get {
                return ResourceManager.GetString("customer_address_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        internal static string customer_address_street {
            get {
                return ResourceManager.GetString("customer_address_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Házszám.
        /// </summary>
        internal static string customer_address_streetnumber {
            get {
                return ResourceManager.GetString("customer_address_streetnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir. szám.
        /// </summary>
        internal static string customer_address_zip {
            get {
                return ResourceManager.GetString("customer_address_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Képviselő.
        /// </summary>
        internal static string customer_contact {
            get {
                return ResourceManager.GetString("customer_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Képviselő.
        /// </summary>
        internal static string customer_contact_name {
            get {
                return ResourceManager.GetString("customer_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelő (opcionális adat).
        /// </summary>
        internal static string customer_data_title {
            get {
                return ResourceManager.GetString("customer_data_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levelezési cím.
        /// </summary>
        internal static string customer_postaladdress {
            get {
                return ResourceManager.GetString("customer_postaladdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        internal static string customer_postaladdress_address {
            get {
                return ResourceManager.GetString("customer_postaladdress_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Város.
        /// </summary>
        internal static string customer_postaladdress_city {
            get {
                return ResourceManager.GetString("customer_postaladdress_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megegyezik az állandó címmel.
        /// </summary>
        internal static string customer_postaladdress_sameasaddress {
            get {
                return ResourceManager.GetString("customer_postaladdress_sameasaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir. szám.
        /// </summary>
        internal static string customer_postaladdress_zip {
            get {
                return ResourceManager.GetString("customer_postaladdress_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új ügyfél.
        /// </summary>
        internal static string customers_create {
            get {
                return ResourceManager.GetString("customers_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ügyfél adatlap módosítása.
        /// </summary>
        internal static string customers_edit {
            get {
                return ResourceManager.GetString("customers_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ügyfelek listája.
        /// </summary>
        internal static string customers_title {
            get {
                return ResourceManager.GetString("customers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégsem.
        /// </summary>
        internal static string general_cancel {
            get {
                return ResourceManager.GetString("general_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenlegi jelszó.
        /// </summary>
        internal static string general_changepassword_currentpassword {
            get {
                return ResourceManager.GetString("general_changepassword_currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új jelszó.
        /// </summary>
        internal static string general_changepassword_password {
            get {
                return ResourceManager.GetString("general_changepassword_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új jelszó megerősítése.
        /// </summary>
        internal static string general_changepassword_passwordconfirm {
            get {
                return ResourceManager.GetString("general_changepassword_passwordconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó frissítése.
        /// </summary>
        internal static string general_changepassword_save {
            get {
                return ResourceManager.GetString("general_changepassword_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen frissítette jelszavát!.
        /// </summary>
        internal static string general_changepassword_success {
            get {
                return ResourceManager.GetString("general_changepassword_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó módosítása.
        /// </summary>
        internal static string general_changepassword_title {
            get {
                return ResourceManager.GetString("general_changepassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Másolás.
        /// </summary>
        internal static string general_clone {
            get {
                return ResourceManager.GetString("general_clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezárás.
        /// </summary>
        internal static string general_close {
            get {
                return ResourceManager.GetString("general_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string general_confirm_dialog_cancel {
            get {
                return ResourceManager.GetString("general_confirm_dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezárás mentés nélkül.
        /// </summary>
        internal static string general_confirm_dialog_ok {
            get {
                return ResourceManager.GetString("general_confirm_dialog_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nem mentett módosítások el fognak veszni. Biztosan folytatja?.
        /// </summary>
        internal static string general_confirm_dialog_question {
            get {
                return ResourceManager.GetString("general_confirm_dialog_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítés.
        /// </summary>
        internal static string general_confirm_dialog_title {
            get {
                return ResourceManager.GetString("general_confirm_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  másolata.
        /// </summary>
        internal static string general_copyof {
            get {
                return ResourceManager.GetString("general_copyof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        internal static string general_data_details {
            get {
                return ResourceManager.GetString("general_data_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        internal static string general_delete {
            get {
                return ResourceManager.GetString("general_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törli?.
        /// </summary>
        internal static string general_delete_dialog_title {
            get {
                return ResourceManager.GetString("general_delete_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen törlés... {0}.
        /// </summary>
        internal static string general_delete_failed {
            get {
                return ResourceManager.GetString("general_delete_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres törlés!.
        /// </summary>
        internal static string general_delete_succes {
            get {
                return ResourceManager.GetString("general_delete_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generál tervező (opcionális adat).
        /// </summary>
        internal static string general_designer_data_title {
            get {
                return ResourceManager.GetString("general_designer_data_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok.
        /// </summary>
        internal static string general_details {
            get {
                return ResourceManager.GetString("general_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen letöltés... {0}.
        /// </summary>
        internal static string general_download_failed {
            get {
                return ResourceManager.GetString("general_download_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás.
        /// </summary>
        internal static string general_edit {
            get {
                return ResourceManager.GetString("general_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem található bejegyzés a &apos;{0}&apos; azonosítóval..
        /// </summary>
        internal static string general_entity_notfound {
            get {
                return ResourceManager.GetString("general_entity_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korlátlan.
        /// </summary>
        internal static string general_limitless {
            get {
                return ResourceManager.GetString("general_limitless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen adat betöltés: {0}.
        /// </summary>
        internal static string general_load_failed {
            get {
                return ResourceManager.GetString("general_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerkesztés.
        /// </summary>
        internal static string general_modify {
            get {
                return ResourceManager.GetString("general_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs megjeleníthető adat..
        /// </summary>
        internal static string general_nodata {
            get {
                return ResourceManager.GetString("general_nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string general_ok {
            get {
                return ResourceManager.GetString("general_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előnézet.
        /// </summary>
        internal static string general_preview {
            get {
                return ResourceManager.GetString("general_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átnevezés.
        /// </summary>
        internal static string general_rename {
            get {
                return ResourceManager.GetString("general_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átnevezés.
        /// </summary>
        internal static string general_rename_dialog_title {
            get {
                return ResourceManager.GetString("general_rename_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen átnevezés: {0}.
        /// </summary>
        internal static string general_rename_failed {
            get {
                return ResourceManager.GetString("general_rename_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres átnevezés!.
        /// </summary>
        internal static string general_rename_success {
            get {
                return ResourceManager.GetString("general_rename_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerepkörök.
        /// </summary>
        internal static string general_roles {
            get {
                return ResourceManager.GetString("general_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        internal static string general_save {
            get {
                return ResourceManager.GetString("general_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés és bezárás.
        /// </summary>
        internal static string general_save_close {
            get {
                return ResourceManager.GetString("general_save_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés bezárás nélkül.
        /// </summary>
        internal static string general_save_continue_editing {
            get {
                return ResourceManager.GetString("general_save_continue_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen mentés... {0}.
        /// </summary>
        internal static string general_save_failed {
            get {
                return ResourceManager.GetString("general_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres mentés!.
        /// </summary>
        internal static string general_save_succes {
            get {
                return ResourceManager.GetString("general_save_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        internal static string general_search {
            get {
                return ResourceManager.GetString("general_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        internal static string general_signin {
            get {
                return ResourceManager.GetString("general_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string general_signin_email {
            get {
                return ResourceManager.GetString("general_signin_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés.
        /// </summary>
        internal static string general_signin_emailconfirmation {
            get {
                return ResourceManager.GetString("general_signin_emailconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítő e-mail újra küldése..
        /// </summary>
        internal static string general_signin_emailconfirmation_title {
            get {
                return ResourceManager.GetString("general_signin_emailconfirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtette jelszavát?.
        /// </summary>
        internal static string general_signin_forgotpassword {
            get {
                return ResourceManager.GetString("general_signin_forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellenőrizze leveleit és kezdeményezze a visszaállítás folyamatot..
        /// </summary>
        internal static string general_signin_forgotpasswordconfirm_desc {
            get {
                return ResourceManager.GetString("general_signin_forgotpasswordconfirm_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó visszaállítás folyamat.
        /// </summary>
        internal static string general_signin_forgotpasswordconfirm_title {
            get {
                return ResourceManager.GetString("general_signin_forgotpasswordconfirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string general_signin_password {
            get {
                return ResourceManager.GetString("general_signin_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítő e-mail kiküldve..
        /// </summary>
        internal static string general_signin_password_verificationsent {
            get {
                return ResourceManager.GetString("general_signin_password_verificationsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megerősítése.
        /// </summary>
        internal static string general_signin_passwordconfirm {
            get {
                return ResourceManager.GetString("general_signin_passwordconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlékezzen rám.
        /// </summary>
        internal static string general_signin_rememberme {
            get {
                return ResourceManager.GetString("general_signin_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail megerősítés újra küldése.
        /// </summary>
        internal static string general_signin_resendconfirmation {
            get {
                return ResourceManager.GetString("general_signin_resendconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó visszaállítása.
        /// </summary>
        internal static string general_signin_reset {
            get {
                return ResourceManager.GetString("general_signin_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kattintson ide a bejelentkezéshez..
        /// </summary>
        internal static string general_signin_resetclickhere {
            get {
                return ResourceManager.GetString("general_signin_resetclickhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó visszaállítása megtörtént..
        /// </summary>
        internal static string general_signin_resetconfirm {
            get {
                return ResourceManager.GetString("general_signin_resetconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó visszaállítása.
        /// </summary>
        internal static string general_signin_resetpassword {
            get {
                return ResourceManager.GetString("general_signin_resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        internal static string general_signout {
            get {
                return ResourceManager.GetString("general_signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen kijelentkezett az alkalmazásból!.
        /// </summary>
        internal static string general_signout_succes {
            get {
                return ResourceManager.GetString("general_signout_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó.
        /// </summary>
        internal static string general_user {
            get {
                return ResourceManager.GetString("general_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás token..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogosultságkezelés.
        /// </summary>
        internal static string menu_access {
            get {
                return ResourceManager.GetString("menu_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string menu_admin {
            get {
                return ResourceManager.GetString("menu_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az épület (tűzszakaszainak) nettó összesített alapterülete.
        /// </summary>
        internal static string net_sum_floor_area {
            get {
                return ResourceManager.GetString("net_sum_floor_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új név.
        /// </summary>
        internal static string new_name {
            get {
                return ResourceManager.GetString("new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új cég hozzáadása.
        /// </summary>
        internal static string tenant_create {
            get {
                return ResourceManager.GetString("tenant_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég módosítása.
        /// </summary>
        internal static string tenant_edit {
            get {
                return ResourceManager.GetString("tenant_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulok.
        /// </summary>
        internal static string tenant_modules {
            get {
                return ResourceManager.GetString("tenant_modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cégek listája.
        /// </summary>
        internal static string tenants_title {
            get {
                return ResourceManager.GetString("tenants_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs hozzáférése a kért tartalomhoz..
        /// </summary>
        internal static string user_accessdenied_desc {
            get {
                return ResourceManager.GetString("user_accessdenied_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hozzáférés megtagadva.
        /// </summary>
        internal static string user_accessdenied_title {
            get {
                return ResourceManager.GetString("user_accessdenied_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új felhasználó hozzáadása.
        /// </summary>
        internal static string user_create {
            get {
                return ResourceManager.GetString("user_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó adatainak módosítása.
        /// </summary>
        internal static string user_edit {
            get {
                return ResourceManager.GetString("user_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zárolt felh..
        /// </summary>
        internal static string user_locked {
            get {
                return ResourceManager.GetString("user_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zárolt fiókkal nem léphet be. Lépjen kapcsolatba a rendszergazdával..
        /// </summary>
        internal static string user_lockout_desc {
            get {
                return ResourceManager.GetString("user_lockout_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókját zárolták..
        /// </summary>
        internal static string user_lockout_title {
            get {
                return ResourceManager.GetString("user_lockout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég.
        /// </summary>
        internal static string user_tenant {
            get {
                return ResourceManager.GetString("user_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerepkör hozzárendelése a felhasználóhoz.
        /// </summary>
        internal static string userroles_edit {
            get {
                return ResourceManager.GetString("userroles_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerepkör.
        /// </summary>
        internal static string userroles_role {
            get {
                return ResourceManager.GetString("userroles_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állapot.
        /// </summary>
        internal static string userroles_status {
            get {
                return ResourceManager.GetString("userroles_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saját magát nem törölheti!.
        /// </summary>
        internal static string users_delete_failedself {
            get {
                return ResourceManager.GetString("users_delete_failedself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó zárolása.
        /// </summary>
        internal static string users_lock {
            get {
                return ResourceManager.GetString("users_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saját magát nem zárolhatja!.
        /// </summary>
        internal static string users_lock_failedself {
            get {
                return ResourceManager.GetString("users_lock_failedself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználói fiók zárolásva. Ezt követően a felhasználó NEM tud bejelentkezni a rendszerbe..
        /// </summary>
        internal static string users_lock_success {
            get {
                return ResourceManager.GetString("users_lock_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogosultságok kezelése.
        /// </summary>
        internal static string users_title {
            get {
                return ResourceManager.GetString("users_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zárolás feloldása.
        /// </summary>
        internal static string users_unlock {
            get {
                return ResourceManager.GetString("users_unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zárolás sikeresen feloldásra került. Ezt követően a felhasználó be tud jelentkezni a rendszerbe..
        /// </summary>
        internal static string users_unlock_success {
            get {
                return ResourceManager.GetString("users_unlock_success", resourceCulture);
            }
        }
    }
}
